port: 4222

jetstream {
  store_dir: "/tmp/furia-bod-jetstream"
}

websocket {
  host: "0.0.0.0"
  port: 9222
  no_tls: true
  allowed_origins: [
    "http://127.0.0.1:5173",
    "http://localhost:5173"
  ]
}
